---
name: userwasil
description: A new Flutter project.
publish_to: none
version: 1.0.0+5
environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  provider: ^6.0.4
  shared_preferences: ^2.0.5
  material_design_icons_flutter: ^7.0.7296
  google_fonts: null
  google_maps_flutter: ^2.0.5
  geolocator: ^10.0.0
  url_launcher: ^6.0.4
  firebase_messaging: null
  connectivity: ^3.0.4
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  flutter_html: ^3.0.0-alpha.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  syncfusion_flutter_datepicker: null
  datepicker_dropdown: ^0.0.7+2
  flutter_zoom_drawer: null
  cloud_firestore: ^4.9.1
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.20
  omni_datetime_picker: ^1.0.8
  intl: ^0.18.1
  geocoding: null
  flutter_local_notifications:
  sizer: null
  scoped_model: null
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  search_map_place_updated: null
  custom_searchable_dropdown: 2.1.1
  pinput: ^3.0.1
  dio: ^ 5.3.3
  card_swiper: ^3.0.1
  share: ^2.0.4
  get: ^4.6.6
  time_range: ^1.1.0
  time_range_picker: ^2.2.0
  date_picker_plus: ^1.1.4
  flutter_spinkit: ^5.2.0
  fancy_shimmer_image: ^2.0.3
dependency_overrides:
  firebase_core_platform_interface: 4.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/lang/en.json
  - assets/lang/ar.json
  - assets/images/
  - assets/images/offer-icon.png
  - assets/images/logo.png
  - assets/images/placeholder/no-product-image.png
  - assets/images/placeholder/no-shop-image.png
  - assets/images/empty-cart.png
  - assets/images/maintenance.png
  - assets/map/shop-pin.png
  - assets/map/delivery-pin.png
  - assets/map/delivery-boy-pin.png
  - assets/map/map-dark-style.txt
  - assets/other/map-snap.png
flutter_intl:
  enabled: true
