class Autogenerated {
  Data? data;
  bool? status;
  String? stateNum;
  String? message;

  Autogenerated({this.data, this.status, this.stateNum, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
    status = json['status'];
    stateNum = json['stateNum'];
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['status'] = status;
    data['stateNum'] = stateNum;
    data['message'] = message;
    return data;
  }
}

class Data {
  List<ShopsModel>? shops;

  Data({this.shops});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['shops'] != null) {
      shops = <ShopsModel>[];
      json['shops'].forEach((v) {
        shops!.add(ShopsModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (shops != null) {
      data['shops'] = shops!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ShopsModel {
  int? id;
  String? nameEn;
  String? nameAr;
  String? email;
  String? mobile;
  int? mobileVerified;
  String? avatarUrl;
  String? license;
  int? isApproval;
  String? referrer;
  String? referrerLink;
  String? shopNameEn;
  String? shopNameAr;
  String? barcode;
  dynamic latitude;
  dynamic longitude;
  String? address;
  int? rating;
  int? deliveryRange;
  int? totalRating;
  int? defaultTax;
  int? availableForDelivery;
  int? open;
  int? categoryId;
  double? distance;
  String? createdAt;
  String? updatedAt;

  ShopsModel(
      {this.id,
      this.nameEn,
      this.nameAr,
      this.email,
      this.mobile,
      this.mobileVerified,
      this.avatarUrl,
      this.license,
      this.isApproval,
      this.referrer,
      this.referrerLink,
      this.shopNameEn,
      this.shopNameAr,
      this.barcode,
      this.latitude,
      this.longitude,
      this.address,
      this.rating,
      this.deliveryRange,
      this.totalRating,
      this.defaultTax,
      this.availableForDelivery,
      this.open,
      this.categoryId,
      this.distance,
      this.createdAt,
      this.updatedAt});

  ShopsModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    nameEn = json['name_en'];
    nameAr = json['name_ar'];
    email = json['email'];
    mobile = json['mobile'];
    mobileVerified = json['mobile_verified'];
    avatarUrl = json['avatar_url'];
    license = json['license'];
    isApproval = json['is_approval'];
    referrer = json['referrer'];
    referrerLink = json['referrer_link'];
    shopNameEn = json['shop_name_en'];
    shopNameAr = json['shop_name_ar'];
    barcode = json['barcode'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    address = json['address'];
    rating = json['rating'];
    deliveryRange = json['delivery_range'];
    totalRating = json['total_rating'];
    defaultTax = json['default_tax'];
    availableForDelivery = json['available_for_delivery'];
    open = json['open'];
    categoryId = json['category_id'];
    distance = json['distance'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name_en'] = nameEn;
    data['name_ar'] = nameAr;
    data['email'] = email;
    data['mobile'] = mobile;
    data['mobile_verified'] = mobileVerified;
    data['avatar_url'] = avatarUrl;
    data['license'] = license;
    data['is_approval'] = isApproval;
    data['referrer'] = referrer;
    data['referrer_link'] = referrerLink;
    data['shop_name_en'] = shopNameEn;
    data['shop_name_ar'] = shopNameAr;
    data['barcode'] = barcode;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['address'] = address;
    data['rating'] = rating;
    data['delivery_range'] = deliveryRange;
    data['total_rating'] = totalRating;
    data['default_tax'] = defaultTax;
    data['available_for_delivery'] = availableForDelivery;
    data['open'] = open;
    data['category_id'] = categoryId;
    data['distance'] = distance;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
