// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACLZ-qThwz-PcpoSNa7TBmGOsDDN8eaMI',
    appId: '1:677303892936:android:bd904d2ce08785f4e01efd',
    messagingSenderId: '677303892936',
    projectId: 'wasilapp-e7679',
    storageBucket: 'wasilapp-e7679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGiPStibHYSA_AF1tpFTDHZpydc__hFJg',
    appId: '1:677303892936:ios:312662cfc77aa50be01efd',
    messagingSenderId: '677303892936',
    projectId: 'wasilapp-e7679',
    storageBucket: 'wasilapp-e7679.appspot.com',
    androidClientId: '677303892936-0he0ajme0cktu8mvoultrgmosje1j49r.apps.googleusercontent.com',
    iosBundleId: 'com.example.userwasil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGiPStibHYSA_AF1tpFTDHZpydc__hFJg',
    appId: '1:677303892936:ios:ee00511731c9f99be01efd',
    messagingSenderId: '677303892936',
    projectId: 'wasilapp-e7679',
    storageBucket: 'wasilapp-e7679.appspot.com',
    androidClientId: '677303892936-0he0ajme0cktu8mvoultrgmosje1j49r.apps.googleusercontent.com',
    iosBundleId: 'com.example.userwasil.RunnerTests',
  );
}
